---
#info: Execute an ipmitool command and writes a log file
- name: Run ipmitool
  connection: local
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
  shell: ipmitool -N 4 -I lanplus -U {{ im_ipmi_user }} -P {{ im_ipmi_password }} -H {{ im_ipmi_host }} {{ ipmi_command }}
  register: shell
  async: 60
  poll: 0
  throttle: 20
  become: false

- name: Check on an async task
  connection: local
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
  async_status:
    jid: '{{ shell.ansible_job_id }}'
  register: job
  until: job.finished
  retries: 1000
  delay: 3
  become: false

- include_role: name=servermonkey.ww_logger
  vars:
    ww_log: '{{ job }}'
    ww_logfile: 'servermonkey.ipmi_{{ ipmi_log }}'